-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Tempo de geração: 19-Abr-2024 às 02:30
-- Versão do servidor: 10.4.27-MariaDB
-- versão do PHP: 8.0.25

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `tcc_andre`
--

-- --------------------------------------------------------

--
-- Estrutura da tabela `questionario1`
--

CREATE TABLE `questionario1` (
  `id_q1` int(11) NOT NULL,
  `pergunta` text NOT NULL,
  `alternativaA` text NOT NULL,
  `alternativaB` text NOT NULL,
  `alternativaC` text NOT NULL,
  `alternaticaCorreta` varchar(1) NOT NULL,
  `Justificativa` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Extraindo dados da tabela `questionario1`
--

INSERT INTO `questionario1` (`id_q1`, `pergunta`, `alternativaA`, `alternativaB`, `alternativaC`, `alternaticaCorreta`, `Justificativa`) VALUES
(1, 'Maria, uma jovem bailarina talentosa, estava ensaiando para uma apresentação importante quando sofreu uma lesão no joelho durante um salto. Ela sentiu uma dor aguda e imediatamente caiu no chão, incapaz de se levantar. Agora, deitada no chão do estúdio de dança, Maria precisa de cuidados urgentes.', 'Massagear vigorosamente o joelho para relaxar os músculos e aliviar a dor.', 'Aplicar calor local sobre o joelho lesionado para aumentar a circulação sanguínea.', 'Imobilizar o joelho afetado utilizando uma tala ou uma bandagem elástica.', 'c', 'Ao imobilizar o joelho lesionado, os enfermeiros garantem que a articulação fique estável, evitando movimentos que possam causar mais danos aos tecidos moles ou agravar a lesão. A imobilização também ajuda a reduzir a dor ao limitar a movimentação da área afetada. O calor local pode aumentar a inflamação e piorar a dor, enquanto a massagem vigorosa pode causar mais danos aos tecidos já lesionados. Portanto, a imobilização é a intervenção de enfermagem mais apropriada para esse caso. '),
(2, 'Clara estava brincando com seu cachorro no parque quando, de repente, o animal a empurrou acidentalmente, fazendo com que ela caísse e torcesse o pulso. Clara sentiu uma dor aguda e imediatamente segurou o pulso, percebendo que algo estava errado. Agora, sentada no chão do parque, ela precisa de cuidados imediatos.', 'Aplicar gelo no pulso torcido para reduzir o inchaço.', 'Realizar movimentos de alongamento no pulso afetado para aliviar a tensão muscular.', 'Colocar uma tala no pulso torcido para imobilizá-lo.', 'c', 'A imobilização do pulso torcido é essencial para evitar movimentos que possam causar mais danos aos ligamentos e músculos da região. A tala oferece suporte e estabilidade, promovendo a recuperação adequada da lesão. Aplicar gelo pode ajudar a reduzir o inchaço, mas sozinho não proporciona a estabilidade necessária. Realizar movimentos de alongamento pode piorar a lesão, aumentando a tensão nos tecidos já comprometidos. Portanto, a imobilização com uma tala é a intervenção de enfermagem mais apropriada para esse caso. '),
(3, 'Natália estava praticando escalada em uma trilha rochosa quando, ao subir em uma saliência, perdeu o equilíbrio e caiu de uma altura considerável, sofrendo uma lesão nas costas. Ela sentiu uma dor intensa na região lombar e teve dificuldade em se mover. Agora, deitada no chão da trilha, Natália precisa urgentemente de cuidados especializados.', 'Realizar massagem nas costas para aliviar a tensão muscular.', 'Aplicar calor local na região lombar para relaxar os músculos.', 'Manter a paciente imóvel e chamar uma equipe de resgate para transporte seguro.', 'c', 'Natália pode ter sofrido uma lesão na coluna vertebral devido à queda, e qualquer movimento inadequado pode piorar a situação, levando a danos neurológicos permanentes. Portanto, é essencial manter a paciente imóvel até que uma equipe médica especializada possa avaliar a extensão da lesão e fornecer transporte seguro para o hospital. Realizar massagem nas costas ou aplicar calor local podem ser prejudiciais, pois podem aumentar a inflamação e causar mais danos aos tecidos lesionados. A prioridade é garantir a segurança da paciente e prevenir complicações adicionais. '),
(4, 'Carlos estava trabalhando em uma construção quando uma barra de ferro caiu sobre seu pé, causando uma lesão grave e um corte profundo. Ele sentiu uma dor excruciante e percebeu que estava perdendo muito sangue rapidamente. Agora, sentado no chão da obra, Carlos precisa de intervenções de enfermagem imediatas.', 'Realizar um curativo compressivo no corte e elevar o pé para reduzir o sangramento.', 'Aplicar uma bolsa de gelo no local da lesão para diminuir o inchaço e a dor.', 'Fazer uma sutura rápida no corte para fechá-lo e impedir mais perda de sangue.', 'a', 'A aplicação de um curativo compressivo no corte ajuda a controlar o sangramento, enquanto elevar o pé auxilia na redução do fluxo sanguíneo para a área afetada, o que é crucial para evitar a perda excessiva de sangue. A pressão exercida pelo curativo ajuda a estancar o sangramento, enquanto a elevação do pé ajuda a reduzir a pressão arterial na região afetada, diminuindo assim o sangramento. Aplicar uma bolsa de gelo pode ser útil para reduzir o inchaço, mas não é a prioridade imediata quando há sangramento intenso. Fazer uma sutura rápida pode ser necessário, mas somente após o controle inicial do sangramento e a avaliação médica adequada. '),
(5, 'Júlia estava praticando ciclismo em uma trilha íngreme quando perdeu o controle da bicicleta e caiu em um barranco, sofrendo uma lesão no braço com fratura exposta. Ela sentiu uma dor aguda e viu seu braço ferido com o osso exposto. Agora, deitada no chão da trilha, Júlia precisa urgentemente de cuidados especializados.', 'Realizar uma limpeza rápida na ferida com água e sabão, seguida de aplicação de um curativo estéril.', 'Tentar reposicionar o osso no local, alinhando-o manualmente, antes de imobilizar o braço.', 'Aplicar compressas quentes na área afetada para aliviar a dor e relaxar os músculos.', 'a', 'Ao realizar uma limpeza rápida na ferida com água e sabão, seguida de aplicação de um curativo estéril, os enfermeiros ajudam a reduzir o risco de infecção, o que é crucial em casos de fratura exposta. Isso ajuda a minimizar a contaminação da ferida e a promover um ambiente propício para a cicatrização. Tentar reposicionar manualmente o osso pode aumentar o risco de danos aos tecidos circundantes e agravar a lesão. Aplicar compressas quentes pode aumentar a inflamação e o sangramento, além de não ser recomendado em casos de fratura exposta. Portanto, a limpeza rápida e a aplicação de um curativo estéril são as intervenções de enfermagem mais adequadas para esse caso. '),
(6, 'Luana, uma adolescente, estava jogando futebol com os amigos quando torceu o tornozelo durante uma partida. Ela sentiu uma dor intensa e teve dificuldade em apoiar o pé no chão. Agora, sentada no gramado, precisa de cuidados imediatos.', 'Aplicar gelo no tornozelo torcido para reduzir o inchaço.', 'Realizar massagem vigorosa no tornozelo afetado para aliviar a dor.', 'Tentar movimentar o tornozelo em todas as direções para verificar a extensão da lesão.', 'a', 'Aplicar gelo no tornozelo torcido é uma intervenção comum e eficaz para reduzir o inchaço e aliviar a dor. O gelo ajuda a constringir os vasos sanguíneos, diminuindo o fluxo sanguíneo para a área afetada e reduzindo a inflamação. Isso pode ajudar a controlar a dor e facilitar a recuperação. Realizar massagem vigorosa pode aumentar a dor e o inchaço, enquanto tentar movimentar o tornozelo pode piorar a lesão, causando mais danos aos ligamentos já comprometidos. Portanto, a aplicação de gelo é a intervenção mais apropriada para este caso. '),
(7, 'Ricardo, um alpinista experiente, estava escalando uma montanha desafiadora quando sofreu uma lesão no braço ao escorregar em uma rocha. Ele sentiu uma dor aguda e notou que seu braço estava deformado. Agora, pendurado em sua corda de segurança, ele precisa de assistência imediata.', 'Tentar realinhar manualmente o braço antes de prosseguir com a descida.', 'Aplicar uma compressa quente na região lesionada para aliviar a dor.', 'Manter o braço imóvel e seguro enquanto aguarda o resgate.', 'c', 'Em situações de lesões traumáticas, como uma possível fratura no braço de Ricardo, é crucial evitar movimentos desnecessários que possam causar mais danos aos tecidos e aumentar a dor. Manter o braço imóvel e seguro é fundamental para prevenir complicações adicionais e garantir uma evacuação segura da montanha. Tentar realinhar manualmente o braço sem conhecimento médico especializado pode piorar a lesão e aumentar o risco de lesões nervosas ou vasculares. Além disso, aplicar uma compressa quente pode aumentar a inflamação e não é apropriado para lesões agudas, especialmente em ambientes de montanha onde é difícil controlar a temperatura. Portanto, a opção mais segura e adequada é manter o braço imóvel e seguro até que a equipe de resgate chegue. '),
(8, 'Isabela estava praticando mergulho em uma caverna subaquática quando foi atingida por uma rocha solta, resultando em uma lesão na cabeça com sangramento. Ela está consciente, mas sente-se tonta e confusa. Agora, flutuando na água escura, Isabela precisa de assistência urgente.', 'Realizar compressão direta na área do sangramento para tentar estancá-lo.', 'Administrar oxigênio suplementar através de um cilindro de mergulho para ajudar na respiração.', 'Manter Isabela calma e imóvel enquanto aguarda o resgate subaquático.', 'c', 'Em uma situação de mergulho subaquático, como a descrita no enunciado, é fundamental priorizar a segurança do paciente e agir de maneira apropriada para evitar complicações adicionais. Manter Isabela calma e imóvel é crucial para evitar movimentos bruscos que possam agravar a lesão na cabeça ou piorar o sangramento. Além disso, como ela está tonta e confusa, qualquer movimento desnecessário pode aumentar o risco de acidentes subaquáticos, como desorientação ou perda de consciência. Aguardar o resgate subaquático é importante para garantir que Isabela seja retirada da água com segurança e receba atendimento médico adequado o mais rápido possível. Realizar compressão direta na área do sangramento pode ser difícil ou ineficaz debaixo d\'água e pode até mesmo piorar a situação. Administrar oxigênio suplementar através de um cilindro de mergulho pode não ser necessário neste momento, já que Isabela está consciente e a principal preocupação é a lesão na cabeça e o sangramento. Portanto, manter Isabela calma e imóvel enquanto aguarda o resgate subaquático é a melhor opção. '),
(9, 'Paulo estava praticando rapel em uma área remota quando escorregou e bateu a cabeça em uma rocha, sofrendo uma lesão na região temporal com perda de sangue. Ele está consciente, mas se queixa de dor intensa e tontura. Agora, pendurado na encosta rochosa, Paulo precisa de assistência urgente.', 'Tentar estabilizar a cabeça de Paulo e aplicar uma bandagem de compressão em torno da área da lesão.', 'Utilizar um torniquete na perna de Paulo para controlar a perda de sangue e evitar choque.', 'Administrar uma injeção de analgésico intramuscular para aliviar a dor de Paulo enquanto espera pelo resgate.', 'a', 'Estabilizar a cabeça de Paulo é crucial para prevenir movimentos que possam agravar a lesão na região temporal, especialmente se houver suspeita de lesão na coluna cervical. Além disso, aplicar uma bandagem de compressão na área da lesão pode ajudar a controlar o sangramento e minimizar a perda de sangue até a chegada da equipe de resgate. Utilizar um torniquete na perna de Paulo, não é apropriado, pois não há indicação de lesão na perna e o torniquete pode agravar a situação ao restringir o fluxo sanguíneo. Administrar uma injeção de analgésico intramuscular pode não ser seguro, uma vez que Paulo está tonto e confuso, e administrar medicamentos em tais circunstâncias pode complicar sua condição. Além disso, a prioridade é controlar o sangramento e estabilizar a lesão na cabeça antes de administrar analgésicos. '),
(10, 'Ana estava fazendo escalada em uma região montanhosa quando uma pedra solta atingiu seu peito, causando dor intensa e dificuldade para respirar. Ela está consciente, mas apresenta sinais de dificuldade respiratória e tosse persistente devido à lesão. Agora, agarrada a uma saliência na rocha, Ana precisa de assistência imediata.', 'Realizar compressões torácicas para tentar aliviar a dificuldade respiratória.', 'Administrar um descongestionante nasal para abrir as vias aéreas de Ana.', 'Posicionar Ana em uma posição semissentada para facilitar a respiração enquanto aguarda o resgate.', 'c', 'Posicionar Ana em uma posição semissentada é a melhor opção para facilitar sua respiração. Isso ajuda a reduzir a dificuldade respiratória ao permitir que os músculos respiratórios funcionem mais eficientemente. Além disso, essa posição ajuda a diminuir a pressão sobre o tórax, o que pode ser especialmente importante se houver suspeita de lesão torácica. Realizar compressões torácicas, não é adequado neste caso, pois Ana está consciente e respirando, e realizar compressões poderia piorar a situação. Administrar um descongestionante nasal, também não é apropriada, pois a dificuldade respiratória de Ana parece ser devido à lesão no peito e não a uma obstrução nasal. Administração desnecessária de medicamentos pode até piorar a situação.');

-- --------------------------------------------------------

--
-- Estrutura da tabela `questionario2`
--

CREATE TABLE `questionario2` (
  `id_q2` int(11) NOT NULL,
  `pergunta` text NOT NULL,
  `alternativaA` text NOT NULL,
  `alternativaB` text NOT NULL,
  `alternativaC` text NOT NULL,
  `alternaticaCorreta` varchar(1) NOT NULL,
  `Justificativa` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Extraindo dados da tabela `questionario2`
--

INSERT INTO `questionario2` (`id_q2`, `pergunta`, `alternativaA`, `alternativaB`, `alternativaC`, `alternaticaCorreta`, `Justificativa`) VALUES
(1, 'Arcantos, um alpinista experiente, estava fazendo uma vídeo chamada durante uma escalada em uma montanha desafiadora quando foi atingido por uma avalanche, resultando em uma lesão na perna com uma fratura exposta. Ele está consciente, mas sente uma dor aguda e percebe que sua perna está deformada. Agora, preso sob a neve, João precisa de assistência urgente.', 'Tentar mobilizar a perna de Arcantos para realinhar o osso antes de prosseguir com a remoção da neve.', 'Utilizar o celular de Arcantos para chamar ajuda enquanto tenta controlar o sangramento da fratura.', 'Aplicar pressão direta na ferida exposta para estancar o sangramento antes de iniciar a remoção da neve.', 'b', 'Dada a situação de Arcantos estar preso sob a neve e apresentando uma fratura exposta, a prioridade é chamar ajuda externa o mais rápido possível. Utilizar o celular para chamar ajuda é uma medida crucial para garantir que uma equipe de resgate seja notificada e possa chegar ao local para fornecer assistência adequada. Tentar mobilizar a perna pode agravar a lesão e causar mais danos aos tecidos, especialmente em uma fratura exposta. Aplicar pressão direta na ferida pode ser difícil de realizar efetivamente sob a neve e pode não ser suficiente para controlar o sangramento em uma situação tão grave. Portanto, a melhor opção é utilizar o celular para chamar ajuda e aguardar a chegada dos profissionais treinados e com equipamentos adequados. '),
(2, 'Durante uma expedição de trekking em uma região remota, Maria sofreu uma queda em um desfiladeiro, resultando em uma lesão na coluna vertebral e paralisia temporária dos membros inferiores. Ela está consciente, mas incapaz de se mover. Agora, aguardando resgate, Maria precisa de cuidados urgentes.', 'Tentar reposicionar Maria manualmente para aliviar a pressão na coluna vertebral antes da chegada do resgate.', 'Administrar medicamentos analgésicos para aliviar a dor de Maria enquanto aguarda a evacuação.', 'Imobilizar Maria completamente e garantir que ela esteja em uma posição estável e segura até a chegada do resgate.', 'c', 'Em casos de lesão na coluna vertebral, é crucial imobilizar o paciente para evitar movimentos que possam agravar a lesão e causar danos adicionais à medula espinhal. Portanto, imobilizar Maria completamente e garantir que ela esteja em uma posição estável e segura é essencial para minimizar o risco de complicações e garantir sua segurança até a chegada do resgate. Tentar reposicionar Maria manualmente pode ser extremamente perigoso, pois movimentos inadequados podem agravar a lesão na coluna vertebral e causar danos permanentes à medula espinhal. Administrar medicamentos analgésicos, pode não ser apropriada, pois a prioridade é garantir a imobilização e a segurança de Maria, e administrar medicamentos sem avaliação médica adequada pode ser arriscado. '),
(3, 'Durante uma expedição de escalada em uma região remota, Joana sofreu uma queda e ficou presa em uma fenda estreita entre duas rochas. Ela está consciente, mas sente uma dor aguda no tórax e tem dificuldade para respirar. Agora, aguardando resgate, Joana precisa de cuidados urgentes.', 'Utilizar cordas e equipamentos de escalada para tentar remover Joana da fenda antes da chegada do resgate.', 'Realizar massagem cardíaca externa para estimular a circulação sanguínea enquanto Joana permanece presa.', 'Aplicar compressas frias no tórax de Joana para reduzir o inchaço e aliviar a dor enquanto aguarda o resgate.', 'c', 'A aplicação de compressas frias no tórax de Joana é a opção mais apropriada para ajudar a reduzir o inchaço e aliviar a dor após uma possível lesão no tórax. Isso pode ajudar a melhorar o desconforto respiratório que ela está enfrentando. No entanto, a aplicação de compressas frias deve ser feita com cuidado para não piorar a situação. Utilizar cordas e equipamentos de escalada para tentar remover Joana da fenda, pode agravar a lesão ou causar danos adicionais se não for realizada corretamente, especialmente considerando sua condição e a possibilidade de uma lesão no tórax. Realizar massagem cardíaca externa, não é apropriado, pois Joana está consciente e respirando. Além disso, realizar massagem cardíaca externa em uma pessoa consciente pode causar danos. '),
(4, 'Durante uma viagem de carro em uma estrada rural, Pedro perdeu o controle do veículo e colidiu com uma árvore. Ele sofreu um ferimento na cabeça com sangramento intenso. Pedro está consciente, mas tonto e confuso. Agora, dentro do carro danificado, ele precisa de cuidados urgentes enquanto aguarda o socorro.', 'Tentar remover Pedro do veículo imediatamente para evitar um incêndio.', 'Administrar aspirina para ajudar a prevenir a formação de coágulos sanguíneos no ferimento.', 'Pressionar firmemente o ferimento na cabeça de Pedro para estancar o sangramento enquanto aguarda o socorro.', 'c', 'Pressionar firmemente o ferimento na cabeça de Pedro é uma medida importante para tentar controlar o sangramento enquanto aguarda o socorro. Isso pode ajudar a minimizar a perda de sangue e reduzir o risco de complicações. No entanto, a pressão deve ser aplicada com cuidado para evitar danos adicionais ao cérebro ou ao crânio. Tentar remover Pedro do veículo imediatamente pode ser perigoso, pois ele pode ter lesões adicionais, especialmente na coluna vertebral, e movê-lo de maneira inadequada pode piorar essas lesões. Administrar aspirina, não é apropriado em uma situação de sangramento intenso, pois a aspirina pode aumentar o risco de sangramento devido às suas propriedades anticoagulantes. '),
(5, 'Durante uma corrida de bicicleta pela cidade, André foi atropelado por um carro em um cruzamento. Ele sofreu uma lesão no braço com um corte profundo e sangramento intenso. André está consciente, mas sente-se fraco devido à perda de sangue. Agora, caído no chão próximo à bicicleta danificada, ele precisa de assistência imediata.', 'Tentar chamar a atenção de um pedestre próximo para pedir ajuda e alertar as autoridades sobre o acidente.', 'Usar um pano para cobrir o corte no braço de André e evitar a entrada de sujeira.', 'Realizar um curativo compressivo no corte do braço de André e aplicar uma bandagem para controlar o sangramento enquanto aguarda o socorro.', 'c', 'Nesta situação de emergência, é fundamental controlar o sangramento para evitar complicações decorrentes da perda excessiva de sangue. Realizar um curativo compressivo no corte do braço de André é uma medida adequada para tentar estancar o sangramento, enquanto a aplicação de uma bandagem ajuda a manter o curativo no lugar e a proteger a área ferida. Tentar chamar a atenção de um pedestre próximo para pedir ajuda e alertar as autoridades, também pode ser útil, mas a prioridade imediata é controlar o sangramento. Uma vez que André esteja com o sangramento sob controle, chamar por ajuda é uma ação importante. Usar um pano para cobrir o corte no braço de André, pode ajudar a proteger a ferida contra a entrada de sujeira, mas não é suficiente para controlar o sangramento intenso. '),
(6, 'Durante uma caminhada noturna na cidade, Marina escorregou em uma calçada molhada e caiu, sofrendo um corte profundo no joelho. Ela está consciente, mas sente uma dor intensa e percebe que está sangrando abundantemente. Agora, sentada no chão próximo ao local da queda, ela precisa de assistência imediata.', 'Tentar sinalizar para um motorista que passa próximo ao local do acidente, pedindo para chamar uma ambulância.', 'Utilizar água potável para limpar o corte no joelho de Marina e evitar infecções.', 'Aplicar pressão direta no corte do joelho de Marina usando um pano limpo para tentar controlar o sangramento enquanto aguarda o socorro.', 'c', 'Nessa situação de emergência, é crucial controlar o sangramento para evitar a perda excessiva de sangue e suas complicações. Aplicar pressão direta no corte do joelho de Marina com um pano limpo é uma medida eficaz para tentar estancar o sangramento. Isso ajudará a reduzir a perda de sangue até que o socorro chegue. Tentar sinalizar para um motorista que passa próximo ao local do acidente, embora possa parecer uma boa ideia para obter ajuda rapidamente, pode não ser seguro e confiável, já que o motorista pode não perceber a situação ou ser incapaz de prestar assistência adequada. Utilizar água potável para limpar o corte no joelho de Marina e evitar infecções, embora seja uma medida importante para prevenir infecções, não aborda diretamente o controle do sangramento, que é a prioridade imediata em uma situação de emergência como essa. '),
(7, 'Durante uma corrida matinal no parque, Rafael foi mordido por um cachorro que estava solto sem coleira. Ele sofreu uma laceração profunda no braço, que está sangrando intensamente. Rafael está consciente, mas sente uma dor aguda e percebe que está perdendo muito sangue. Agora, sentado em um banco próximo à trilha onde ocorreu o incidente, ele precisa de assistência imediata.', 'Utilizar a própria camiseta para fazer um torniquete no braço de Rafael e tentar estancar o sangramento.', 'Chamar um funcionário do parque para relatar o incidente e pedir ajuda imediata.', 'Aplicar pressão direta na ferida de Rafael usando um pedaço de pano limpo para controlar o sangramento enquanto aguarda o socorro.', 'c', 'Em casos de sangramento intenso, como o descrito no enunciado, a prioridade é controlar a perda de sangue para evitar complicações graves. Aplicar pressão direta na ferida com um pedaço de pano limpo é uma medida eficaz para tentar estancar o sangramento até que o socorro chegue. Isso ajuda a reduzir a perda de sangue e minimizar o risco de choque hipovolêmico. Utilizar a própria camiseta para fazer um torniquete no braço de Rafael, não é recomendado, pois torniquetes podem causar danos aos tecidos e nervos e devem ser usados apenas em casos de hemorragias graves e descontroladas, o que não parece ser o caso aqui. Chamar um funcionário do parque para relatar o incidente e pedir ajuda imediata, embora seja uma ação importante para notificar as autoridades sobre o ocorrido, não aborda diretamente a necessidade urgente de controlar o sangramento de Rafael. '),
(8, 'Durante um passeio de bicicleta pela cidade, Carla testemunhou um acidente de trânsito envolvendo dois carros. Um dos motoristas parece estar inconsciente e preso às ferragens, enquanto o outro motorista parece estar em estado de choque, incapaz de agir. Carla, que é enfermeira, está consciente da necessidade de intervenção imediata.', 'Tentar remover imediatamente o motorista inconsciente das ferragens para avaliar suas condições.', 'Pedir ajuda a transeuntes para acalmar o motorista em estado de choque enquanto Carla atende ao motorista inconsciente.', 'Avaliar rapidamente a cena do acidente e garantir que não haja riscos adicionais para a segurança de Carla antes de prestar socorro.', 'c', 'Ao se deparar com um acidente de trânsito, é crucial garantir a segurança pessoal antes de iniciar qualquer intervenção. Avaliar rapidamente a cena do acidente permite que Carla identifique quaisquer perigos iminentes, como vazamento de combustível, fogo, fiação elétrica exposta, entre outros, que possam representar riscos adicionais. Garantir a segurança de si mesma e de outros transeuntes é a prioridade para evitar mais lesões. Tentar remover imediatamente o motorista inconsciente das ferragens, pode colocar tanto a vítima quanto Carla em maior perigo, especialmente se houver riscos de lesões na coluna vertebral ou fraturas ósseas. Pedir ajuda a transeuntes para acalmar o motorista em estado de choque, embora seja importante fornecer apoio emocional, não aborda diretamente a avaliação da cena do acidente para garantir a segurança geral. '),
(9, 'Durante um dia de compras em um centro comercial movimentado, Luana presenciou uma pessoa desmaiando subitamente perto da praça de alimentação. A pessoa parece estar consciente, mas apresenta respiração superficial e pele pálida. Luana, que tem conhecimentos básicos em primeiros socorros, sabe que precisa agir rapidamente.', 'Procurar pela equipe de segurança do shopping para que chame uma ambulância imediatamente enquanto ela tenta acordar a pessoa desmaiada.', 'Procurar por uma loja próxima que venda suprimentos médicos e buscar uma máscara de oxigênio para ajudar na respiração da pessoa desmaiada.', 'Deitar a pessoa desmaiada de costas e elevar as pernas dela para facilitar o fluxo sanguíneo enquanto aguarda a chegada da ajuda.', 'c', 'Ao deparar-se com uma pessoa desmaiada, é importante adotar medidas que visem a melhorar o fluxo sanguíneo para o cérebro. Deitar a pessoa de costas e elevar as pernas dela ajuda a aumentar o retorno venoso para o coração, melhorando assim a circulação sanguínea e o aporte de oxigênio ao cérebro. Isso pode auxiliar na recuperação da consciência da pessoa e evitar complicações decorrentes do desmaio. Procurar pela equipe de segurança do shopping para que chame uma ambulância imediatamente enquanto ela tenta acordar a pessoa desmaiada, embora seja importante solicitar ajuda profissional, não aborda diretamente a posição adequada da vítima para melhorar a circulação sanguínea. Procurar por uma loja próxima que venda suprimentos médicos e buscar uma máscara de oxigênio para ajudar na respiração da pessoa desmaiada, pode ser demorada e não é uma medida prioritária em um caso de desmaio. '),
(10, 'Durante uma festa de aniversário em um parque, Kenshin presenciou uma criança engasgando com um pedaço de bolo. A criança está visivelmente angustiada, incapaz de falar ou tossir, e começa a ficar com a pele arroxeada. Kenshin, que é um socorrista voluntário, sabe que precisa agir rapidamente para salvar a criança.', 'Realizar a manobra de Heimlich na criança para tentar desobstruir as vias aéreas.', 'Oferecer água à criança para ajudá-la a engolir o pedaço de bolo.', 'Colocar a criança de bruços no colo de João e realizar tapinhas nas costas para tentar remover o pedaço de bolo.', 'a', 'A manobra de Heimlich é uma técnica de primeiros socorros indicada para desobstruir as vias aéreas superiores em casos de engasgo. Ao aplicar a manobra corretamente, ela pode ajudar a expelir o objeto estranho que está causando a obstrução, permitindo que a criança respire novamente. Como a criança está incapaz de tossir ou falar e começa a ficar com a pele arroxeada, indica que a obstrução das vias aéreas é grave e requer uma intervenção imediata, como a manobra de Heimlich. Oferecer água à criança para ajudá-la a engolir o pedaço de bolo, pode piorar a situação, pois a água pode empurrar ainda mais o objeto para baixo, agravando a obstrução. Colocar a criança de bruços no colo de Kenshin e realizar tapinhas nas costas, é uma técnica usada em bebês para lidar com obstruções por objetos maiores, mas não é indicada para crianças maiores ou adultos e pode ser ineficaz ou até mesmo perigosa nesse caso.');

-- --------------------------------------------------------

--
-- Estrutura da tabela `questionario3`
--

CREATE TABLE `questionario3` (
  `id_q3` int(11) NOT NULL,
  `pergunta` text NOT NULL,
  `alternativaA` text NOT NULL,
  `alternativaB` text NOT NULL,
  `alternativaC` text NOT NULL,
  `alternaticaCorreta` varchar(1) NOT NULL,
  `Justificativa` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Extraindo dados da tabela `questionario3`
--

INSERT INTO `questionario3` (`id_q3`, `pergunta`, `alternativaA`, `alternativaB`, `alternativaC`, `alternaticaCorreta`, `Justificativa`) VALUES
(1, 'Durante um piquenique em um parque, Ana percebeu que um idoso que estava próximo dela começou a ter dificuldades para respirar. Ele está agitado, com respiração rápida e superficial, e parece estar entrando em pânico. Ana, que possui conhecimentos básicos em primeiros socorros, sabe que precisa agir rapidamente para ajudar o idoso.', 'Inclinar o idoso para trás e levantar os braços dele para facilitar a respiração.', 'Realizar compressões abdominais no idoso para tentar aliviar a dificuldade respiratória.', 'Manter o idoso sentado e acalmá-lo, incentivando-o a respirar profundamente e lentamente enquanto aguarda o socorro.', 'c', 'A ação mais apropriada neste cenário é acalmar o idoso e incentivá-lo a respirar profundamente e lentamente. Isso pode ajudar a diminuir a agitação e reduzir a respiração rápida e superficial. Muitas vezes, a dificuldade respiratória está associada ao pânico, e acalmar o paciente pode melhorar a respiração. Além disso, manter o idoso sentado é uma posição que facilita a respiração e evita complicações como aspiração em caso de vômito. Inclinar o idoso para trás e levantar os braços dele, não é recomendada, pois essa manobra pode dificultar ainda mais a respiração, especialmente se o idoso estiver tendo dificuldades respiratórias. Realizar compressões abdominais, também não é indicada neste caso, pois não aborda a causa subjacente da dificuldade respiratória e pode até mesmo causar danos se não for realizada corretamente. '),
(2, 'Durante um evento esportivo em um estádio lotado, João percebeu uma pessoa próxima a ele que de repente começou a mostrar sinais de uma possível parada cardíaca. A pessoa está inconsciente, não está respirando e não tem pulso palpável. João, que é um bombeiro voluntário, sabe que precisa agir rapidamente para tentar salvar a vida dessa pessoa.', 'Começar a realizar massagem cardíaca imediatamente enquanto aguarda a chegada da equipe médica.', 'Tentar acordar a pessoa inconsciente chacoalhando-a e gritando o nome dela.', 'Procurar por um desfibrilador externo automático (DEA) nas proximidades e começar a preparar o equipamento para uso.', 'a', 'A massagem cardíaca é uma intervenção crucial em casos de parada cardíaca, pois ajuda a manter a circulação sanguínea, fornecendo oxigênio aos órgãos vitais, como o cérebro. Nesse caso, em que a pessoa está inconsciente, não está respirando e não possui pulso palpável, as diretrizes de primeiros socorros recomendam iniciar imediatamente a massagem cardíaca até que a equipe médica chegue. Cada minuto sem intervenção reduz drasticamente as chances de sobrevivência da vítima. Tentar acordar a pessoa inconsciente chacoalhando-a e gritando o nome dela, não é apropriada em uma situação de parada cardíaca, pois a pessoa não responde a estímulos externos devido à falta de circulação sanguínea adequada para o cérebro. Procurar por um desfibrilador externo automático (DEA) nas proximidades e começar a preparar o equipamento para uso, embora seja uma medida importante, a prioridade imediata é iniciar a massagem cardíaca, pois o DEA é mais eficaz quando combinado com a massagem cardíaca e a sua disponibilidade pode não ser imediata. '),
(3, 'Durante um acampamento noturno em uma trilha na floresta, Carla notou que seu amigo Lucas começou a apresentar sinais de hipotermia após uma mudança brusca de temperatura. Lucas está tremendo incontrolavelmente, com dificuldade para falar e se mover. Carla, que tem conhecimentos básicos em primeiros socorros, sabe que precisa ajudar Lucas imediatamente.', 'Retirar as roupas molhadas de Lucas e colocar roupas secas e quentes para ajudar a elevar a temperatura corporal dele.', 'Preparar uma bebida quente para Lucas, como chá ou sopa, para ajudar a aquecê-lo por dentro.', 'Construir um abrigo improvisado com galhos e folhas para proteger Lucas do vento e da umidade, enquanto o mantém aquecido até que a temperatura ambiente melhore.', 'a', 'Em casos de hipotermia, é essencial remover as roupas molhadas, pois elas contribuem para a perda de calor do corpo. Trocá-las por roupas secas e quentes ajudará a preservar o calor corporal de Lucas e a elevar sua temperatura. Isso é especialmente importante em ambientes ao ar livre, onde não há acesso imediato a aquecimento ou outros recursos médicos. Preparar uma bebida quente para Lucas, embora possa ajudar a aquecê-lo por dentro, não é tão eficaz quanto a remoção das roupas molhadas e o aquecimento externo. Além disso, a preparação de uma bebida quente pode demandar tempo e recursos que podem não estar disponíveis no momento. Construir um abrigo improvisado, é importante para proteger Lucas do vento e da umidade, mas não é suficiente para tratar a hipotermia. O aquecimento direto do corpo através da troca de roupas molhadas é uma medida prioritária. '),
(4, 'Durante uma viagem de carro em uma estrada deserta, Pedro e sua família encontraram um acidente envolvendo um veículo capotado. Ao se aproximarem, perceberam que uma das pessoas envolvidas no acidente estava inconsciente e com uma ferida profunda na perna, que estava sangrando abundantemente. Pedro, que tem conhecimentos básicos em primeiros socorros, sabe que precisa agir rapidamente para ajudar a vítima.', 'Tentar estancar o sangramento aplicando pressão direta na ferida com um pano limpo ou bandagem.', 'Remover a pessoa do veículo capotado e levá-la para um local mais seguro antes de prestar qualquer tipo de assistência.', 'Buscar água potável para limpar a ferida da pessoa antes de aplicar qualquer tipo de curativo.', 'a', 'Em casos de ferimentos com sangramento abundante, como uma ferida profunda na perna, a prioridade é controlar a hemorragia para evitar a perda excessiva de sangue, o que pode levar a complicações graves. Aplicar pressão direta na ferida com um pano limpo ou bandagem é uma medida eficaz para estancar o sangramento. Isso ajuda a comprimir os vasos sanguíneos e a reduzir o fluxo sanguíneo, o que é crucial para estabilizar a vítima até a chegada de socorro especializado. Remover a pessoa do veículo capotado e levá-la para um local mais seguro, pode expor a vítima a movimentos desnecessários e aumentar o risco de lesões adicionais, especialmente se houver suspeita de lesões na coluna vertebral. A prioridade é estabilizar a vítima no local do acidente e garantir sua segurança. Buscar água potável para limpar a ferida, embora seja importante manter a ferida limpa para prevenir infecções, não deve ser a primeira ação tomada, pois não aborda diretamente o controle do sangramento. A limpeza da ferida pode ser realizada após o sangramento estar controlado. '),
(5, 'Durante um passeio de bicicleta, Maria deparou-se com uma cena preocupante: um pedestre foi atingido por um carro próximo a um cruzamento movimentado. Ao se aproximar, Maria percebeu que o pedestre estava consciente, mas apresentava uma fratura exposta na perna, com sangramento visível. Maria, que possui conhecimentos básicos em primeiros socorros, sabe que precisa agir rapidamente para ajudar a vítima.', 'Tentar imobilizar a perna fraturada utilizando um pedaço de madeira ou similar, e aplicar um torniquete acima do local da fratura para controlar o sangramento.', 'Elevar a perna fraturada da vítima para reduzir o inchaço enquanto aguarda a chegada do socorro.', 'Aplicar pressão direta sobre a ferida com um pano limpo ou bandagem para controlar o sangramento e, em seguida, imobilizar a perna utilizando um apoio improvisado.', 'c', 'Em casos de fraturas expostas com sangramento, a prioridade é controlar a hemorragia para evitar a perda excessiva de sangue. A aplicação de pressão direta sobre a ferida com um pano limpo ou bandagem é uma medida eficaz para estancar o sangramento. Uma vez que o sangramento esteja controlado, é importante imobilizar a perna fraturada para evitar movimentos que possam causar mais lesões. Tentar imobilizar a perna fraturada utilizando um pedaço de madeira ou similar e aplicar um torniquete acima do local da fratura, não é recomendada, pois pode causar danos adicionais aos tecidos e nervos, além de aumentar o risco de complicações. Elevar a perna fraturada da vítima para reduzir o inchaço, embora possa ser útil para reduzir o inchaço, não aborda diretamente o controle do sangramento, que é a prioridade imediata nesse caso. '),
(6, 'Durante um passeio no parque, Joana testemunhou um acidente em que uma pessoa caiu de uma altura significativa e parece ter sofrido uma lesão no pescoço. A vítima está consciente, mas se queixa de dormência e fraqueza em ambos os braços. Joana, que tem conhecimentos básicos em primeiros socorros, sabe que precisa agir com cautela para evitar agravar a lesão.', 'Tentar mover a cabeça da vítima para verificar se há alguma lesão visível no pescoço.', 'Manter a cabeça e o pescoço da vítima imobilizados na posição em que foram encontrados e chamar imediatamente uma equipe de resgate.', 'Inclinar a cabeça da vítima para trás para facilitar a respiração e aliviar qualquer possível obstrução das vias aéreas.', 'b', 'Em casos de suspeita de lesão no pescoço, é fundamental manter a cabeça e o pescoço da vítima imobilizados para evitar movimentos que possam agravar a lesão, especialmente a medula espinhal. Qualquer movimento brusco pode causar danos adicionais e resultar em consequências graves, como paralisia permanente. Portanto, a melhor ação é manter a vítima na posição em que foi encontrada e solicitar ajuda médica imediata. Tentar mover a cabeça da vítima para verificar se há alguma lesão visível no pescoço, é perigosa, pois pode piorar a lesão e causar danos à medula espinhal. Inclinar a cabeça da vítima para trás para facilitar a respiração, não é recomendada em casos de suspeita de lesão no pescoço, pois pode aumentar o risco de danos à coluna cervical. '),
(7, 'Durante uma trilha em uma montanha, Lucas deparou-se com um acidente envolvendo um alpinista que escorregou e caiu em uma área rochosa. Ao se aproximar, Lucas percebeu que o alpinista estava consciente, mas que ele estava segurando o pescoço com as duas mãos e parecia ter dificuldade para mover os braços e as pernas. Lucas, que tem conhecimentos básicos em primeiros socorros, sabe que precisa agir com cautela para prestar assistência ao alpinista.', 'Tentar acalmar o alpinista e encorajá-lo a tentar mover os membros afetados para verificar a extensão da lesão no pescoço.', 'Manter o alpinista imóvel e apoiar sua cabeça e pescoço para evitar movimentos que possam agravar a lesão.', 'Administrar analgésicos ao alpinista para aliviar a dor enquanto aguarda o resgate chegar.', 'b', 'Em casos de suspeita de lesão no pescoço, é crucial manter o paciente imóvel e apoiar a cabeça e o pescoço para evitar movimentos que possam prejudicar a coluna cervical e a medula espinhal. Qualquer movimento brusco pode resultar em danos adicionais e agravar a lesão. Portanto, a prioridade é garantir a imobilização do alpinista até que a equipe de resgate chegue. Tentar acalmar o alpinista e encorajá-lo a mover os membros afetados, é perigosa, pois pode resultar em danos adicionais à medula espinhal se houver uma lesão no pescoço. Administrar analgésicos, não é apropriada neste caso, pois não aborda diretamente a imobilização da lesão no pescoço e pode mascarar os sintomas, dificultando a avaliação médica adequada. '),
(8, 'Durante um churrasco em família, Isabela estava preparando alimentos na churrasqueira quando um incidente ocorreu e ela acabou queimando o antebraço direito com o contato direto com a grelha quente. Isabela está com muita dor e percebe uma vermelhidão intensa na área afetada. Seu primo João, que tem conhecimentos básicos em primeiros socorros, está próximo e quer ajudá-la.', 'Colocar gelo imediatamente sobre a queimadura para aliviar a dor e reduzir a inflamação.', 'Cobrir a queimadura com uma gaze estéril e procurar por uma pomada cicatrizante para aplicar na área afetada.', 'Manter a queimadura sob água corrente fria por pelo menos 10 minutos para resfriar a pele e aliviar a dor.', 'c', 'Em casos de queimaduras, é essencial resfriar imediatamente a área afetada para interromper o processo de queimadura e minimizar o dano tecidual. A água corrente fria é eficaz para resfriar a pele queimada, reduzir a inflamação e aliviar a dor. Manter a queimadura sob água corrente por pelo menos 10 minutos é uma medida importante para ajudar na recuperação e reduzir o risco de complicações. Colocar gelo imediatamente sobre a queimadura, não é recomendada, pois o gelo pode causar danos adicionais à pele e aumentar o desconforto. Cobrir a queimadura com uma gaze estéril e procurar por uma pomada cicatrizante, também não é a melhor abordagem inicial, pois a prioridade é resfriar a área queimada para evitar danos mais graves. '),
(9, 'Durante um acampamento, Pedro estava preparando o jantar quando uma garrafa de álcool utilizada para acender a fogueira acabou derramando sobre sua perna, resultando em uma queimadura grave. Pedro está com uma dor intensa e percebe que uma grande área de sua perna está vermelha, com bolhas e áreas de pele carbonizada. Seu amigo Miguel, que tem algum conhecimento em primeiros socorros, está próximo e quer ajudá-lo.', 'Retirar imediatamente as roupas da área afetada e aplicar pomadas caseiras, como pasta de dente, para aliviar a dor e promover a cicatrização.', 'Cobrir a queimadura com um pano úmido e frio e, em seguida, chamar uma ambulância para transportar Pedro para o hospital mais próximo.', 'Abrir as bolhas com uma agulha esterilizada e aplicar um curativo sobre a área queimada para protegê-la de infecções.', 'b', 'Em casos de queimaduras graves, como descrito, é crucial buscar assistência médica profissional o mais rápido possível. Cobrir a queimadura com um pano úmido e frio ajuda a aliviar a dor, reduzir a inflamação e evitar danos adicionais à pele. Chamar uma ambulância para transportar Pedro para o hospital é fundamental para receber tratamento adequado, como a limpeza da queimadura, aplicação de curativos especializados e, se necessário, a administração de analgésicos e fluidos intravenosos. Retirar imediatamente as roupas da área afetada e aplicar pomadas caseiras, como pasta de dente, não é recomendada para queimaduras graves, pois isso pode causar mais dor e aumentar o risco de infecção. Abrir as bolhas com uma agulha esterilizada, também não é recomendada, pois isso pode aumentar o risco de infecção e agravar a lesão. '),
(10, 'Durante um churrasco em família, João sofreu uma queimadura enquanto manuseava o carvão na churrasqueira. A queimadura é profunda e extensa, cobrindo grande parte de seu antebraço esquerdo. João está sentindo muita dor e percebe que a pele está vermelha, com áreas de bolhas e descolamento. Sua irmã, Ana, que possui conhecimentos básicos em primeiros socorros, está próxima e quer ajudá-lo.', 'Aplicar manteiga sobre a queimadura para aliviar a dor e promover a cicatrização.', 'Remover as bolhas e a pele solta e cobrir a queimadura com um curativo aderente.', 'Cobrir a queimadura com uma compressa de água gelada e, em seguida, aplicar um curativo esterilizado.', 'c', 'Neste caso, a aplicação de uma compressa de água gelada ajuda a reduzir a dor, controlar a inflamação e minimizar o dano tecidual. No entanto, é importante evitar o uso de água extremamente gelada, pois pode causar danos à pele. Após a aplicação da compressa, cobrir a queimadura com um curativo esterilizado ajuda a proteger a área afetada contra infecções externas e promove um ambiente de cicatrização adequado. Aplicar manteiga sobre a queimadura, não é recomendada, pois pode aumentar o risco de infecção e não oferece nenhum benefício terapêutico real. Remover as bolhas e a pele solta, não é apropriada, pois isso pode expor a área afetada a infecções e aumentar a dor do paciente. Além disso, a remoção das bolhas pode aumentar o risco de complicações, como infecções e cicatrizes.');

-- --------------------------------------------------------

--
-- Estrutura da tabela `questionario_alunos`
--

CREATE TABLE `questionario_alunos` (
  `id_questionario_alunos` int(11) NOT NULL,
  `pergunta_1` varchar(2) DEFAULT NULL,
  `pergunta_2` varchar(2) DEFAULT NULL,
  `pergunta_3` varchar(2) DEFAULT NULL,
  `pergunta_4` varchar(2) DEFAULT NULL,
  `pergunta_5` varchar(2) DEFAULT NULL,
  `pergunta_6` varchar(2) DEFAULT NULL,
  `pergunta_7` varchar(2) DEFAULT NULL,
  `pergunta_8` varchar(2) DEFAULT NULL,
  `pergunta_9` varchar(2) DEFAULT NULL,
  `pergunta_10` varchar(2) DEFAULT NULL,
  `pergunta_11` varchar(2) DEFAULT NULL,
  `pergunta_12` varchar(2) DEFAULT NULL,
  `pergunta_13` varchar(2) DEFAULT NULL,
  `pergunta_14` varchar(2) DEFAULT NULL,
  `pergunta_15` varchar(2) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Estrutura da tabela `respostas`
--

CREATE TABLE `respostas` (
  `id_resposta` int(11) NOT NULL,
  `nome_aluno` varchar(255) NOT NULL,
  `turma` varchar(255) NOT NULL,
  `id_pergunta_tela1` int(11) NOT NULL,
  `alternativa_pergunta_tela1` varchar(2) NOT NULL,
  `alternativa_correta_tela1` varchar(2) NOT NULL,
  `id_pergunta_tela2` int(11) NOT NULL,
  `alternativa_pergunta_tela2` varchar(2) NOT NULL,
  `alternativa_correta_tela2` varchar(2) NOT NULL,
  `id_pergunta_tela3` int(11) NOT NULL,
  `alternativa_pergunta_tela3` varchar(2) NOT NULL,
  `alternativa_correta_tela3` varchar(2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Extraindo dados da tabela `respostas`
--

INSERT INTO `respostas` (`id_resposta`, `nome_aluno`, `turma`, `id_pergunta_tela1`, `alternativa_pergunta_tela1`, `alternativa_correta_tela1`, `id_pergunta_tela2`, `alternativa_pergunta_tela2`, `alternativa_correta_tela2`, `id_pergunta_tela3`, `alternativa_pergunta_tela3`, `alternativa_correta_tela3`) VALUES
(1, '', '', 0, '', '', 0, '', '', 0, '', '');

--
-- Índices para tabelas despejadas
--

--
-- Índices para tabela `questionario1`
--
ALTER TABLE `questionario1`
  ADD PRIMARY KEY (`id_q1`);

--
-- Índices para tabela `questionario2`
--
ALTER TABLE `questionario2`
  ADD PRIMARY KEY (`id_q2`);

--
-- Índices para tabela `questionario3`
--
ALTER TABLE `questionario3`
  ADD PRIMARY KEY (`id_q3`);

--
-- Índices para tabela `questionario_alunos`
--
ALTER TABLE `questionario_alunos`
  ADD PRIMARY KEY (`id_questionario_alunos`);

--
-- Índices para tabela `respostas`
--
ALTER TABLE `respostas`
  ADD PRIMARY KEY (`id_resposta`);

--
-- AUTO_INCREMENT de tabelas despejadas
--

--
-- AUTO_INCREMENT de tabela `questionario1`
--
ALTER TABLE `questionario1`
  MODIFY `id_q1` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;

--
-- AUTO_INCREMENT de tabela `questionario2`
--
ALTER TABLE `questionario2`
  MODIFY `id_q2` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;

--
-- AUTO_INCREMENT de tabela `questionario3`
--
ALTER TABLE `questionario3`
  MODIFY `id_q3` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;

--
-- AUTO_INCREMENT de tabela `questionario_alunos`
--
ALTER TABLE `questionario_alunos`
  MODIFY `id_questionario_alunos` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT de tabela `respostas`
--
ALTER TABLE `respostas`
  MODIFY `id_resposta` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
